# Generated by Django 3.2.7 on 2023-10-20 06:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entries', '0002_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryentry',
            name='favorite',
            field=models.ManyToManyField(blank=True, default=None, related_name='favorite_entry', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
