# Generated by Django 3.2.7 on 2023-10-20 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0004_alter_diaryentry_favorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diaryentry',
            old_name='favorite',
            new_name='favorites',
        ),
    ]
